version: '3.5'

services:
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile-dev
    volumes:
      - './services/database:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/football_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/football_test
    depends_on:
      - users-db
  users-db:
    build:
      context: ./services/database/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile-dev
    volumes:
      - './services/ui:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - login
      - weather
      - database
      - league_table
      - best_of_division
      - fixture_info
      - team_info
  login:
    build:
      context: services/login
      dockerfile: Dockerfile-dev
    volumes:
      - './services/login:/usr/src/app'
    ports:
      - 5014:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - database
  weather:
    build:
      context: ./services/weather
      dockerfile: Dockerfile-dev
    volumes:
      - './services/weather:/usr/src/app'
    ports:
      - 5016:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  league_table:
    build:
      context: ./services/league_table
      dockerfile: Dockerfile-dev
    volumes:
      - './services/league_table:/usr/src/app'
    ports:
      - 5017:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  best_of_division:
    build:
      context: ./services/best_of_division
      dockerfile: Dockerfile-dev
    volumes:
      - './services/best_of_division:/usr/src/app'
    ports:
      - 5018:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  fixture_info:
    build:
      context: ./services/fixture_info
      dockerfile: Dockerfile-dev
    volumes:
      - './services/fixture_info:/usr/src/app'
    ports:
      - 5019:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  team_info:
    build:
      context: ./services/team_info
      dockerfile: Dockerfile-dev
    volumes:
      - './services/team_info:/usr/src/app'
    ports:
      - 5020:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
  assign_referee:
    build:
      context: ./services/assign_referee
      dockerfile: Dockerfile-dev
    volumes:
      - './services/assign_referee:/usr/src/app'
    ports:
      - 5021:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig